"""
Data schemas for LLM explanation request inputs and structured response outputs.
"""

from typing import Dict, List, Optional
from pydantic import BaseModel, Field


class LLMExplanationRequest(BaseModel):
    """Request payload to generate an LLM explanation for an existing analysis result."""
    analysis_id: str = Field(..., description="UUID of completed video analysis session")
    mode: Optional[str] = Field("explanation", description="Mode ('explanation', 'executive_summary', 'limitations')")


class LLMExplanationResponse(BaseModel):
    """Structured human-readable explanation generated by LLM explanation layer."""
    analysis_id: str = Field(..., description="UUID of analyzed session")
    executive_summary: str = Field(..., description="Concise executive summary of model findings")
    signal_breakdown: Dict[str, str] = Field(..., description="Explanations for Spatial ViT, Frequency FFT, and Temporal Bi-LSTM signals")
    suspicious_frame_notes: str = Field(..., description="Explanation of flagged suspicious frames")
    responsible_ai_disclaimer: str = Field(..., description="Safety disclaimer regarding model uncertainty and human review requirements")
    generator_provider: str = Field(..., description="LLM provider name or local guardrailed synthesis engine")
